name = "ssr-opengraph-beta"
compatibility_date = "2023-06-22"
main = "src/index.tsx"

[env.beta]
name = "ssr-opengraph-beta"
routes = [
  "*.kodadot.xyz/",
  "*.kodadot.xyz/blog/*",
  "*.kodadot.xyz/ahp/gallery/*",
  "*.kodadot.xyz/ahp/detail/*",
  "*.kodadot.xyz/ahp/collection/*",
  "*.kodadot.xyz/ahp/drops/*",
  "*.kodadot.xyz/ahp/u/*",
  "*.kodadot.xyz/ahk/gallery/*",
  "*.kodadot.xyz/ahk/detail/*",
  "*.kodadot.xyz/ahk/collection/*",
  "*.kodadot.xyz/ahk/drops/*",
  "*.kodadot.xyz/ahk/u/*",
  "*.koda.art/",
  "*.koda.art/blog/*",
  "*.koda.art/ahp/gallery/*",
  "*.koda.art/ahp/detail/*",
  "*.koda.art/ahp/collection/*",
  "*.koda.art/ahp/drops/*",
  "*.koda.art/ahp/u/*",
  "*.koda.art/ahk/gallery/*",
  "*.koda.art/ahk/detail/*",
  "*.koda.art/ahk/collection/*",
  "*.koda.art/ahk/drops/*",
  "*.koda.art/ahk/u/*",
]

[env.beta.site]
bucket = "./public"

[env.production]
name = "ssr-opengraph"
routes = [
  "kodadot.xyz/",
  "kodadot.xyz/blog/*",
  "kodadot.xyz/ahp/gallery/*",
  "kodadot.xyz/ahp/detail/*",
  "kodadot.xyz/ahp/collection/*",
  "kodadot.xyz/ahp/drops/*",
  "kodadot.xyz/ahp/u/*",
  "kodadot.xyz/ahk/gallery/*",
  "kodadot.xyz/ahk/detail/*",
  "kodadot.xyz/ahk/collection/*",
  "kodadot.xyz/ahk/drops/*",
  "kodadot.xyz/ahk/u/*",
  "koda.art/",
  "koda.art/blog/*",
  "koda.art/ahp/gallery/*",
  "koda.art/ahp/detail/*",
  "koda.art/ahp/collection/*",
  "koda.art/ahp/drops/*",
  "koda.art/ahp/u/*",
  "koda.art/ahk/gallery/*",
  "koda.art/ahk/detail/*",
  "koda.art/ahk/collection/*",
  "koda.art/ahk/drops/*",
  "koda.art/ahk/u/*",
]

[env.production.site]
bucket = "./public"
