name = "nft-storage"
compatibility_date = "2023-01-01"

[vars]
DEDICATED_GATEWAY = 'https://r2.infura-ipfs.io'
DEDICATED_BACKUP_GATEWAY = 'https://r2-backup.infura-ipfs.io'
NFTSTORAGE_IPFS = 'https://nftstorage.link'
CF_IMAGE_ACCOUNT = 'b3f9fdfd827152316d080a5ddee59915'
CF_IMAGE_ID = 'jk5b6spi_m_-9qC4VTnjpg'

[[r2_buckets]]
binding = 'R2_BUCKET'
bucket_name = 'stockpile'
preview_bucket_name = 'alpha-stockpile'
