name = "profile"
main = "src/index.ts"
compatibility_date = "2023-04-20"
entry_point = "src/index.ts"


[[d1_databases]]
binding = "PROFILE_DB"
database_name = "enjoyer"
database_id = "fbff8ead-be12-4dd1-b10d-4b727b6034e8"