name = "hypergate"
account_id = "b3f9fdfd827152316d080a5ddee59915"
workers_dev = true
compatibility_date = "2022-01-20"
main = "build/worker/shim.mjs"

[vars]
WORKERS_RS_VERSION = "0.0.11"
PINATA_GATEWAY = 'https://kodadot.mypinata.cloud'

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"


[[r2_buckets]]
binding = 'MY_BUCKET'
bucket_name = 'ipfs-assets'
preview_bucket_name = 'ipfs-assets-dev'

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
