compatibility_date = "2023-06-21"
name = "ssr-opengraph"
main = "src/index.tsx"

[env.beta]
routes = [
  "*.kodadot.xyz/*/gallery/*",
  "*.kodadot.xyz/*/detail/*",
  "*.kodadot.xyz/*/collection/*",
  "*.kodadot.xyz/*/u/*",
]

[env.production]
routes = [
  "kodadot.xyz/*/gallery/*",
  "kodadot.xyz/*/detail/*",
  "kodadot.xyz/*/collection/*",
  "kodadot.xyz/*/u/*",
]
