name = "ssr-opengraph-beta"
compatibility_date = "2023-06-22"
main = "src/index.tsx"
routes = [
  "*.kodadot.xyz/",
  "*.kodadot.xyz/blog/*",
  "*.kodadot.xyz/rmrk/gallery/*",
  "*.kodadot.xyz/rmrk/detail/*",
  "*.kodadot.xyz/rmrk/collection/*",
  "*.kodadot.xyz/rmrk/u/*",
  "*.kodadot.xyz/ksm/gallery/*",
  "*.kodadot.xyz/ksm/detail/*",
  "*.kodadot.xyz/ksm/collection/*",
  "*.kodadot.xyz/ksm/u/*",
  "*.kodadot.xyz/bsx/gallery/*",
  "*.kodadot.xyz/bsx/detail/*",
  "*.kodadot.xyz/bsx/collection/*",
  "*.kodadot.xyz/bsx/u/*",
  "*.kodadot.xyz/ahp/gallery/*",
  "*.kodadot.xyz/ahp/detail/*",
  "*.kodadot.xyz/ahp/collection/*",
  "*.kodadot.xyz/ahp/drops/*",
  "*.kodadot.xyz/ahp/u/*",
  "*.kodadot.xyz/ahk/gallery/*",
  "*.kodadot.xyz/ahk/detail/*",
  "*.kodadot.xyz/ahk/collection/*",
  "*.kodadot.xyz/ahk/drops/*",
  "*.kodadot.xyz/ahk/u/*",
  "*.kodadot.xyz/sandbox.html*"
]

[site]
bucket = "./public"

[env.beta]
name = "ssr-opengraph-beta"

[env.production]
name = "ssr-opengraph"
routes = [
  "kodadot.xyz/",
  "kodadot.xyz/blog/*",
  "kodadot.xyz/rmrk/gallery/*",
  "kodadot.xyz/rmrk/detail/*",
  "kodadot.xyz/rmrk/collection/*",
  "kodadot.xyz/rmrk/u/*",
  "kodadot.xyz/ksm/gallery/*",
  "kodadot.xyz/ksm/detail/*",
  "kodadot.xyz/ksm/collection/*",
  "kodadot.xyz/ksm/u/*",
  "kodadot.xyz/bsx/gallery/*",
  "kodadot.xyz/bsx/detail/*",
  "kodadot.xyz/bsx/collection/*",
  "kodadot.xyz/bsx/u/*",
  "kodadot.xyz/ahp/gallery/*",
  "kodadot.xyz/ahp/detail/*",
  "kodadot.xyz/ahp/collection/*",
  "kodadot.xyz/ahp/drops/*",
  "kodadot.xyz/ahp/u/*",
  "kodadot.xyz/ahk/gallery/*",
  "kodadot.xyz/ahk/detail/*",
  "kodadot.xyz/ahk/collection/*",
  "kodadot.xyz/ahk/drops/*",
  "kodadot.xyz/ahk/u/*",
  "kodadot.xyz/sandbox.html*"
]

[env.production.site]
bucket = "./public"
